import axios from 'axios'

export const openIMRs=[
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"1","agingDays":"10","inc":"INC01001567","reporter":"Jensen","category":"Payment","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"2","agingDays":"5","inc":"INC01001568","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":6,"maxSLALostBy":"MYCA","issueWith":"CFE","id":"3","agingDays":"2","inc":"INC01001569","reporter":"Jensen","category":"Payment","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"4","agingDays":"10","inc":"INC01001560","reporter":"Jensen","category":"Vendor","createdOn":"01/30/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":5,"maxSLALostBy":"CLP","issueWith":"CLP","id":"5","agingDays":"5","inc":"INC01001571","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"6","agingDays":"5","inc":"INC01001572","reporter":"Jensen","category":"Payment","createdOn":"01/30/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"CFE","issueWith":"MYCA","id":"7","agingDays":"5","inc":"INC01001573","reporter":"Jensen","category":"Vendor","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"CLP","id":"8","agingDays":"5","inc":"INC01001574","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Loan tequest has failed for 5 times","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":4,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"9","agingDays":"8","inc":"INC01001575","reporter":"Jensen","category":"Vendor","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"GCAP","issueWith":"Business","id":"10","agingDays":"5","inc":"INC01001576","reporter":"Jensen","category":"Loan","createdOn":"01/25/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"CLP","id":"11","agingDays":"5","inc":"INC01001577","reporter":"Jensen","category":"Customer","createdOn":"02/05/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":12,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"12","agingDays":"5","inc":"INC01001578","reporter":"Jensen","category":"Customer","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"GCAP","issueWith":"CLP","id":"13","agingDays":"5","inc":"INC01001579","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":6,"maxSLALostBy":"MYCA","issueWith":"DXP","id":"14","agingDays":"5","inc":"INC01001580","reporter":"Jensen","category":"Customer","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"15","agingDays":"3","inc":"INC01001581","reporter":"Jensen","category":"Payment","createdOn":"02/05/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"CLP","issueWith":"CFE","id":"16","agingDays":"5","inc":"INC01001582","reporter":"Jensen","category":"Customer","createdOn":"01/28/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"CFE","issueWith":"MYCA","id":"17","agingDays":"4","inc":"INC01001583","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
	{"maxSLALost":8,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"18","agingDays":"10","inc":"INC01001584","reporter":"Jensen","category":"Payment","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"CLP","id":"19","agingDays":"5","inc":"INC01001585","reporter":"Jensen","category":"Loan","createdOn":"01/25/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"20","agingDays":"2","inc":"INC01001586","reporter":"Jensen","category":"Payment","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"CRPS","issueWith":"CFE","id":"21","agingDays":"10","inc":"INC01001587","reporter":"Jensen","category":"Vendor","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":15,"maxSLALostBy":"MYCA","issueWith":"Business","id":"22","agingDays":"15","inc":"INC01001588","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"CLP","id":"23","agingDays":"5","inc":"INC01001589","reporter":"Jensen","category":"Payment","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"24","agingDays":"5","inc":"INC01001590","reporter":"Jensen","category":"Vendor","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":10,"maxSLALostBy":"CLP","issueWith":"DXP","id":"25","agingDays":"5","inc":"INC01001591","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Loan tequest has failed for 5 times","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"26","agingDays":"8","inc":"INC01001592","reporter":"Jensen","category":"Vendor","createdOn":"02/05/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"27","agingDays":"5","inc":"INC01001593","reporter":"Jensen","category":"Loan","createdOn":"01/25/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"EMM","issueWith":"CLP","id":"28","agingDays":"5","inc":"INC01001594","reporter":"Jensen","category":"Customer","createdOn":"01/28/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"EMM","issueWith":"MYCA","id":"29","agingDays":"5","inc":"INC01001595","reporter":"Jensen","category":"Customer","createdOn":"02/05/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":8,"maxSLALostBy":"MYCA","issueWith":"CFE","id":"30","agingDays":"5","inc":"INC01001596","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"31","agingDays":"5","inc":"INC01001597","reporter":"Jensen","category":"Customer","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"DXP","id":"32","agingDays":"3","inc":"INC01001598","reporter":"Jensen","category":"Payment","createdOn":"01/28/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":2,"maxSLALostBy":"CLP","issueWith":"MYCA","id":"33","agingDays":"5","inc":"INC01001599","reporter":"Jensen","category":"Customer","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
    {"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"CLP","id":"34","agingDays":"4","inc":"INC01001600","reporter":"Jensen","category":"Loan","createdOn":"02/05/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"}

];


export const imrsInOtherTeamsQueue = [
{"maxSLALost":7,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"1","agingDays":"10","inc":"INC01001567","reporter":"Jensen","category":"Vendor","createdOn":"01/10/19","status":"In Progress","subject":"Vendor addition failed","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"CFE","issueWith":"CFE","id":"2","agingDays":"5","inc":"INC01001568","reporter":"Jensen","category":"Linkage","createdOn":"01/13/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":2,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"3","agingDays":"2","inc":"INC01001569","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Unable to take loan","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":8,"maxSLALostBy":"GCAP","issueWith":"GCAP","id":"4","agingDays":"10","inc":"INC01001560","reporter":"Jensen","category":"Loan","createdOn":"01/12/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"5","agingDays":"5","inc":"INC01001571","reporter":"Jensen","category":"Loan","createdOn":"01/13/19","status":"In Progress","subject":"Elligibility Issue","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":4,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"6","agingDays":"5","inc":"INC01001572","reporter":"Jensen","category":"Linkage","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"DXP","issueWith":"DXP","id":"7","agingDays":"5","inc":"INC01001573","reporter":"Jensen","category":"Linkage","createdOn":"01/10/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":4,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"8","agingDays":"5","inc":"INC01001574","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Loan tequest has failed for 5 times","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":6,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"9","agingDays":"8","inc":"INC01001575","reporter":"Jensen","category":"Linkage","createdOn":"01/10/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"DXP","issueWith":"DXP","id":"10","agingDays":"5","inc":"INC01001576","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Elligibility Issue","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":4,"maxSLALostBy":"DXP","issueWith":"DXP","id":"11","agingDays":"5","inc":"INC01001577","reporter":"Jensen","category":"Linkage","createdOn":"01/13/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":4,"maxSLALostBy":"DXP","issueWith":"DXP","id":"12","agingDays":"5","inc":"INC01001578","reporter":"Jensen","category":"Loan","createdOn":"12/31/18","status":"In Progress","subject":"Unable to take loan","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"DXP","issueWith":"DXP","id":"13","agingDays":"5","inc":"INC01001579","reporter":"Jensen","category":"Loan","createdOn":"01/14/19","status":"In Progress","subject":"Vendor addition failed","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"14","agingDays":"5","inc":"INC01001580","reporter":"Jensen","category":"Linkage","createdOn":"12/31/18","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":2,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"15","agingDays":"3","inc":"INC01001581","reporter":"Jensen","category":"Loan","createdOn":"01/12/19","status":"In Progress","subject":"Elligibility Issue","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"CRPS","issueWith":"CRPS","id":"16","agingDays":"5","inc":"INC01001582","reporter":"Jensen","category":"Linkage","createdOn":"01/13/19","status":"In Progress","subject":"Cannot link products","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"},
{"maxSLALost":3,"maxSLALostBy":"MYCA","issueWith":"MYCA","id":"17","agingDays":"4","inc":"INC01001583","reporter":"Jensen","category":"Loan","createdOn":"01/14/19","status":"In Progress","subject":"Vendor addition failed","description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"}
];



export const imrDetails = {
        "id":"1",
        "agingDays":"10",
        "inc":"INC01001567",
        "reporter":"Jensen",
        "category":"Payment",
        "createdOn":"12/31/18",
        "status":"In Progress",
        "subject":"Cannot link products",
        "description":"12/30- Created the ticket.\n\n 12/31- Routed to MYCA"
    };

    export const openIMRs1 = axios.get('http://localhost:8080/RESTfulExample/rest/incidents').then(response =>{
        return response.data
    })